apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: backup
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: backup
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: test
            name: backup
            resources: {}
          restartPolicy: OnFailure
  schedule: '* 0 * * *'
status: {}
